name: Deploy-to-Preprod

on:
  push:
    branches: [ "final" ]

env:
  PROJECT_ID: jkcement-hackathon
  SERVICE_BACKEND: jkcement-backend
  SERVICE_FRONTEND: jkcement-frontend
  REGION: asia-south1
  REPO: hackathon
  ENVIRONMENT: prod
  VERSION: ${{ github.sha }}

jobs:
  deploy-backend:
    name: Deploy Backend
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/753775305781/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'deploy-demo@jkcement-hackathon.iam.gserviceaccount.com'
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        run: |
          cd backend
          docker build --build-arg VERSION=${{ env.VERSION }} \
            -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_BACKEND }}:latest" .
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_BACKEND }}:latest"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: '${{ env.SERVICE_BACKEND }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_BACKEND }}:latest'
          project_id: '${{ env.PROJECT_ID }}'
          env_vars: |-
            PROJECT=${{ env.PROJECT_ID }}
            PROJECT_ID=${{ env.PROJECT_ID }}
            LOCATION=${{ env.REGION }}
            DATABASE_URL=sqlite+aiosqlite:///./cement_plant.db
          flags: |-
            --ingress=all
            --allow-unauthenticated
            --vpc-connector=projects/jkcement-hackathon/locations/asia-south1/connectors/jk-cement
            --vpc-egress=all-traffic
            --service-account=sreenivas@jkcement-hackathon.iam.gserviceaccount.com
            --min-instances=1
            --max-instances=2
            --memory=4Gi
            --cpu=2
            --execution-environment=gen2
            --timeout=1200

      - name: Show Backend Service URL
        run: echo "✅ Backend deployed at ${{ steps.deploy.outputs.url }}"

  deploy-frontend:
    name: Deploy Frontend
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/753775305781/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'deploy-demo@jkcement-hackathon.iam.gserviceaccount.com'
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet

      - name: Build and Push Docker image
        run: |
          cd frontend
          docker build --build-arg VERSION=${{ env.VERSION }} \
            -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_FRONTEND }}:latest" .
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_FRONTEND }}:latest"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: '${{ env.SERVICE_FRONTEND }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO }}/${{ env.SERVICE_FRONTEND }}:latest'
          project_id: '${{ env.PROJECT_ID }}'
          env_vars: |-
            PROJECT=${{ env.PROJECT_ID }}
            PROJECT_ID=${{ env.PROJECT_ID }}
            LOCATION=${{ env.REGION }}
            DATABASE_URL=sqlite:///./cement_plant.db
          flags: |-
            --ingress=all
            --allow-unauthenticated
            --vpc-connector=projects/jkcement-hackathon/locations/asia-south1/connectors/jk-cement
            --vpc-egress=all-traffic
            --service-account=sreenivas@jkcement-hackathon.iam.gserviceaccount.com
            --min-instances=1
            --max-instances=2
            --memory=4Gi
            --cpu=2
            --execution-environment=gen2
            --timeout=1200

      - name: Show Frontend Service URL
        run: echo "✅ Frontend deployed at ${{ steps.deploy.outputs.url }}"
